#!/bin/bash
# Copyright 2022 SuperDARN Canada, University of Saskatchewan
# Author: Theodore Kolkman
#
# Script that pings the Borealis computer, and sends a text alert if the computer is unreachable.
# This script should be run via site CD or DDS computer, so that text alerts are only sent if only
# Borealis is unreachable, but CD or DDS are still online. If the whole site is down, there is
# little we can do, and we don't want to be notified.
#
# Dependencies:
#   - mutt (Installed with zypper)
#   - postfix enabled and started 
#   - BOREALIS_IP defined in ~/.bashrc
#   - Email-to-text addresses defined correctly
#   - Line 'myorigin = smtp.servername.suffix' must be added to /etc/postfix/main.cf to stop cell
#     providers from blocking the computer sending via mutt

###################################################################################################

source "${HOME}/.bashrc"

# Define text numbers to alert here
# Correct cell provider email-to-sms addresses must be used too
ADDRESSES=(3062313083@sms.sasktel.com)

SERVER_DOWN="false"

MESSAGE="SuperDARN Borealis Alert:\n\n${RADARID}borealis is down"
echo -e $MESSAGE

###################################################################################################

printf "Executing $0 on $(hostname) for ${RADARID}\n"
date --utc "+%Y%m%d %H:%M:%S UTC"

# If ping fails, Borealis is unreachable and return value will be 1
ping -c1 -W1 $BOREALIS_IP
if [[ $? -ne 0 ]]; then
    echo 'Borealis is down'
    SERVER_DOWN="true"
fi

# Send text alert if Borealis unreachable.
if [[ $SERVER_DOWN == "true" ]]; then
    echo "Sending text alerts to:"
    printf '%s\n' "${ADDRESSES[@]}"
    for address in $ADDRESSES; do
        echo -e $MESSAGE | mutt -- $address
    done
fi
echo ""

